"calibre-gui" = ""
"chromium" = ""
"code-oss" = ""
"discord" = ""
"draw.io" = ""
"firefox" = ""
"kitty" = ""
"krita" = ""
"libreoffice-calc" = ""
"libreoffice-writer" = ""
"mpv" = ""
"nemo" = ""
"neomutt" = ""
"org.pwmt.zathura" = ""
"org.qutebrowser.qutebrowser" = ""
"paperwork" = ""
"pavucontrol" = ""
"peek" = ""
"qutepreview" = ""
"scli" = ""
"transmission-gtk" = ""
"vimiv" = ""
"virt-manager" = ""
"xplr" = ""

"DEFAULT" = ""
